### ISSUE TITLE
缺少一份产品使用说明书（文档）

### ISSUE THREAD

**Issue by ByCnck** [AschPlatform/asch-docs#13]
当前很多人（包括普通用户、前后端开发人员）对产品的基本功能不了解（有些概念不明白，比如什么是UIA、和XAS的区别是什么），而现有的功能说明文档都已帖子的形式存在，比如注册Asch账户、设置二级密码、发行资产等

**Comment by liangpeili** [comment]
Getting Started + 5 分钟入门已解决。
