### ISSUE TITLE
注册应用到主链上报"Server error: Invalid dapp delegates"

### ISSUE THREAD

**Issue by Hitheworld** [AschPlatform/asch-docs#18]
asch服务已启动,但到注册应用到主链上时报"Server error: Invalid dapp delegates",创建的Dapp目录是另外在外层新建的还是在asch里面创建的,再运行  asch-cli registerdapp -f dapp.json -e "someone manual strong movie roof episode eight spatial brown soldier soup motor"

**Comment by ByCnck** [comment]
给定的受托人公钥数组长度，不满足你设定的最少受托人个数
