### ISSUE TITLE
部署一个DApp到节点

### ISSUE THREAD

**Issue by yuxingwei** [AschPlatform/asch-docs#47]
##### **1. 安装最新的asch-cli**

```bash
npm install -g asch-cli
```

##### **2. 准备受托人账户**

每个 Dapp 都有独立的受托人， 这些受托人负责区块的生产、资产的转账并且获取手续费。 一个Dapp最少有5个受托人， 最多101个。 在注册Dapp之前， 需要先生成受托人，收集受托人的公钥。

使用`asch-cli crypto -g` 来生成账户，需要输入想要生产的账户个数

```bash
root@asch~$ asch-cli crypto -g
? Enter number of accounts to generate 5
[ { address: 'ALEPemqWYMcEgxGPJkyp7e85umrvMCasCd',
    secret: 'mix differ fresh hobby tool cabin doctor share impact divert subject citizen',
    publicKey: '6ec699c5bb73bed443a36f84281d41c12398aa485ff067cd61f045a5bc13180c' },
  { address: 'A5UCP4Y61qBKp6GHSvDiozBoVbhuFbZMqR',
    secret: 'marriage census fetch bean swift town issue double segment pizza monitor abuse',
    publicKey: 'a21c74ff391af26eeb923cf3e2230d70c8b2f5c91de8f507ddd7f10fe6dc28c9' },
  { address: 'A7vQ39WxcrSb8bcxZGQh5UPtVjnQK4cCCq',
    secret: 'use assume pear bicycle tennis usage answer blush able almost notable spy',
    publicKey: 'd8039e6c583aeab1ec7a94610c664a753d1889c4095d3e16887a80c7cc11855e' },
  { address: 'AB3tTx7TavyNiDn43cUkW5867PCAFWb3wL',
    secret: 'festival gallery oyster lumber mimic gain wear twelve diesel hero kiss copy',
    publicKey: 'b114cc5ea3100230518f91c363406463a9a495b966455a0566256bfd8bb3016d' },
  { address: 'A86WxERXPsNyyKFiDZdjY4GoSFRMcfTVn5',
    secret: 'hen brain duty blast summer figure blouse elephant aunt then surround security',
    publicKey: '5e2744e8dbfb48fc4fb92e0da0e69a498cb89a577ab85c4b7a9017992ac04038' } ]
Done
```

##### **3. 在主链注册DApp**

使用asch-cli命令在节点去注册一个DApp应用.

首先需要准备一个dapp.json文件用来配置应用的基本信息，下面给出json内容格式

```json
{
  "name": "asch-dapp-helloworld",          //应用名字
  "link": "https://github.com/a1300/chians/archive/master.zip",  //应用的安装包链接
  "category": 1,                 //类别  
  "desc": "Provide an example",  //描述
  "tags": "asch,chain,demo",     //标签
  "icon": "http://o7dyh3w0x.bkt.clouddn.com/chian.png",    //应用的logo
  "type": 0,    //类型
  "delegates": [      //受托人的密钥
    "6ec699c5bb73bed443a36f84281d41c12398aa485ff067cd61f045a5bc13180c",
    "a21c74ff391af26eeb923cf3e2230d70c8b2f5c91de8f507ddd7f10fe6dc28c9",
    "d8039e6c583aeab1ec7a94610c664a753d1889c4095d3e16887a80c7cc11855e",
    "b114cc5ea3100230518f91c363406463a9a495b966455a0566256bfd8bb3016d",
    "5e2744e8dbfb48fc4fb92e0da0e69a498cb89a577ab85c4b7a9017992ac04038"
  ],
  "unlockDelegates": 3    //跨链操作需要几个受托人签名
}
```
使用asch-cli的registerchain命令注册DApp

关于asch-cli的命令详见文档<https://github.com/AschPlatform/asch-cli/tree/master/>

```bash
root@asch~$ asch-cli  -P 4096 registerchain -e "stone elephant caught wrong spend traffic success fetch inside blush virtual element" -f dapp.json
```

到此，可以在主链的应用商店中看到自己注册的DApp了。当然，这仅仅只是在主链中注册了一个应用（就如上面操作的DApp，此时这个应用是空的）。下面以asch的helloworld的demo示例来演示将一个应用注册并部署到节点。

##### **1. 先下载demo源码**   

**Github链接 <https://github.com/AschPlatform/asch-dapp-helloworld.git>** 

```bash
root@asch~$ git clone https://github.com/AschPlatform/asch-dapp-helloworld.git
root@asch~$ cd asch-dapp-helloworld
```

说明：asch-dapp-helloworld是一个dapp的模板，里面有一些配置文件包括config.json，dapp.json，genesis.json等。

详情介绍请见DApp目录结构 **<https://github.com/AschPlatform/dappbook/blob/master/ch13.md>**

按照上面的asch-cli注册的方法修改此目录下的dapp.json

如下：

```json
{
  "name": "asch-dapp-helloworld",          //应用名字
  "link": "https://github.com/a1300/chians/archive/master.zip",  //应用的安装包链接
  "category": 1,                 //类别  
  "desc": "Provide an example",  //描述
  "tags": "asch,chain,demo",     //标签
  "icon": "http://o7dyh3w0x.bkt.clouddn.com/chian.png",    //应用的logo
  "type": 0,    //类型
  "delegates": [      //受托人的密钥
    "6ec699c5bb73bed443a36f84281d41c12398aa485ff067cd61f045a5bc13180c",
    "a21c74ff391af26eeb923cf3e2230d70c8b2f5c91de8f507ddd7f10fe6dc28c9",
    "d8039e6c583aeab1ec7a94610c664a753d1889c4095d3e16887a80c7cc11855e",
    "b114cc5ea3100230518f91c363406463a9a495b966455a0566256bfd8bb3016d",
    "5e2744e8dbfb48fc4fb92e0da0e69a498cb89a577ab85c4b7a9017992ac04038"
  ],
  "unlockDelegates": 3    //跨链操作需要几个受托人签名
}
```

使用asch-cli  registerchain命令注册

```bash
root@asch~$ asch-cli  -P 4096 registerchain -e "stone elephant caught wrong spend traffic success fetch inside blush virtual element" -f dapp.json
0de8d19c5866940af0e09245b8352acd42d14075960335453f758f481f0319d3
```

前提保证 "stone elephant caught wrong spend traffic success fetch inside blush virtual element" 的账户里面是有>=100XAS币的.成功以后会返回交易id，此ID也是注册的应用ID.

下面配置该应用的config.json。

在注册应用的时候填写了委托人的私钥，而config.json里面配置的就是委托人的账号密码

```json
{
  "peers": [],
  "secrets": [
    "mix differ fresh hobby tool cabin doctor share impact divert subject citizen",
    "marriage census fetch bean swift town issue double segment pizza monitor abuse",
    "use assume pear bicycle tennis usage answer blush able almost notable spy",
    "festival gallery oyster lumber mimic gain wear twelve diesel hero kiss copy",
    "hen brain duty blast summer figure blouse elephant aunt then surround security"
  ]
}
```

五个委托人私钥和密码相对应.

**2. 部署应用到节点**

先将这个工程目录拷贝到节点 asch/chains/下

```bash
root@asch~$ cp -r asch-dapp-helloworld asch/chains/
```

这一步是将asch-dapp-helloworld这个应用拷贝到节点上。此时，应用的前端界面是保存在/asch-dapp-helloworld/下的index.html文件，需要将这个文件拷贝导节点的 asch/public/dist/chains/asch-dapp-helloworld(需要创建)/目录下（DApp的前端）

```bash
root@asch~$ cp asch/chains/asch-dapp-helloworld/public/index.html asch/public/dist/chains/asch-dapp-helloworld/
```

完成上述步骤后，此时访问**http://host:4096/chains/asch-dapp-helloworld/** 就可以访问应用的主页了

附：如果访问的时候出现8080服务未启动error，那是因为注册的应用还没有进行后台服务配置，可以将上一步的index.html文件用**https://github.com/AschPlatform/asch-dapp-helloworld/blob/26a6af56082988447c7e4097e7251150e3a17220/public/index.html** 这个文件替换即可

**Comment by bassjobsen** [comment]
@yuxingwei thank for your clear explanation about how in stall a Dapp! You  uses the new `registerchain` command of asch-cli, according to https://github.com/AschPlatform/asch-cli/issues/23#issuecomment-411667010 the latest version of asch-cli is the development branch. Is that right?  I also wonder which version of asch-js should used with that; https://github.com/AschPlatform/asch-cli/blob/develop/package.json#L21. Cause we had issues like https://github.com/AschPlatform/asch-js/pull/14, https://github.com/AschPlatform/asch-js/issues/12 and https://github.com/AschPlatform/asch-js/issues/11

**Comment by liangpeili** [comment]
@bassjobsen Just published the new doc, https://github.com/AschPlatform/asch-docs/blob/master/dapp/hello_world/zh-cn.md. I will translate it into english as soon as possible
