### ISSUE TITLE
AschJS.dapp.createDapp is not a function

### ISSUE THREAD

**Issue by anshuman-singh-93** [AschPlatform/asch-docs#8]
when i run asch-cli dapps -a ,and fill all the information ,then finally it says createDapp is not a function

**Comment by zhouxunAtSC** [comment]
it's AschJS.dapp.createDApp

**Comment by chengling** [comment]
i have the same problem

**Comment by sqfasd** [comment]
Will be fixed after  the latest develop documents released

**Comment by ByCnck** [comment]
The lastest codes have fixed the problem.
